// "Volume 2" shablonining interfeys matnlari: o'zbek (lotin), o'zbek (kirill), rus.
// Tillar va mijoz matnlarining tarjimasi — src/lib/i18n.js (osmon shabloni bilan umumiy).
// T — joriy til matnlari (setLang() bilan almashtiriladi; import qilganlar yangi qiymatni ko'radi).
import { cyr } from './lib/i18n.js';
import { MONTHS, WEEKDAYS, WEEKDAYS_SHORT } from './lib/config.js';

const UZ = {
  months: MONTHS, // saytlardagi avvalgi yozilish bilan bir xil
  monthsNom: MONTHS,
  weekdays: WEEKDAYS,
  weekdaysShort: WEEKDAYS_SHORT,
  envelopeTo: 'Taklifnoma',
  envelopeHint: 'Ochish uchun muhrni bosing',
  envelopeOpen: 'Taklifnomani ochish',
  heroCaption: 'To‘yga taklifnoma',
  greeting: 'Hurmatli mehmonimiz!',
  invitation: (g, b) => `Sizni farzandlarimiz ${g} va ${b}ning nikoh to‘yi marosimiga taklif etamiz.`,
  closing: 'Tashrifingiz biz uchun katta sharaf!',
  down: 'Pastga',
  respectfully: 'Hurmat bilan,',
  when: 'Qachon?',
  at: (t) => `soat ${t}`,
  gcal: 'Google Taqvimga qo‘shish',
  ics: 'Taqvimga saqlash (.ics)',
  countdownTitle: 'To‘yimizgacha qoldi',
  units: { days: 'kun', hours: 'soat', minutes: 'daqiqa', seconds: 'soniya' },
  countdownEnded: 'To‘y bo‘lib o‘tdi. Barchangizga tashrifingiz uchun rahmat!',
  countdownStarted: 'To‘y boshlandi! Sizni kutib qolamiz 🤍',
  calTitle: (names) => `${names} — to‘y`,
  where: 'Qayerda?',
  gmap: 'Google Maps',
  ymap: 'Yandex Xarita',
  guestEyebrow: 'To‘y kechasi mehmoni',
  noticesTitle: 'Muhim iltimoslar',
  program: 'To‘y dasturi',
  dress: 'Dress-kod',
  gallery: 'Lahzalarimiz',
  swipe: 'Suring →',
  zoom: 'Rasmni kattalashtirish',
  close: 'Yopish',
  deadline: (d, m) => `Iltimos, ${d}-${m}gacha javob bering`,
  rsvpTitle: 'Tashrifingizni tasdiqlang',
  name: 'Ismingiz *',
  phone: 'Telefon raqamingiz',
  canCome: 'Kela olasizmi? *',
  yes: 'Albatta kelaman',
  no: 'Afsuski, kela olmayman',
  howMany: 'Necha kishi bo‘lasiz?',
  wishes: 'Tilaklaringiz',
  send: 'Javobni yuborish',
  wishesTitle: 'Tilaklar',
  contacts: 'Savollar bo‘lsa',
  musicOn: 'Musiqani yoqish',
  musicOff: 'Musiqani o‘chirish',
  langSwitch: 'Tilni almashtirish',
  skip: 'O‘tkazib yuborish',
  preludeBtn: 'Ko‘rish',
  preludeHint: 'ovoz bilan tomosha qiling',
  closedCall: 'Javoblar qabul qilish muddati tugagan. Savollar bo‘lsa, quyidagi raqamlarga qo‘ng‘iroq qiling.',
  closed: 'Javoblar qabul qilish muddati tugagan.',
  errName: 'Iltimos, ismingizni kiriting.',
  errAttending: 'Iltimos, kela olishingizni belgilang.',
  errPhone: 'Telefon raqami noto‘g‘ri kiritilgan.',
  sending: 'Yuborilmoqda…',
  errConfigCall: 'Hozircha javobni qabul qilib bo‘lmadi. Iltimos, birozdan so‘ng urinib ko‘ring yoki telefon orqali bog‘laning.',
  errConfig: 'Hozircha javobni qabul qilib bo‘lmadi. Iltimos, birozdan so‘ng qayta urinib ko‘ring.',
  errGeneric: 'Xatolik yuz berdi. Iltimos, birozdan so‘ng qayta urinib ko‘ring.',
  errNetwork: 'Internet aloqasini tekshirib, qayta urinib ko‘ring.',
  change: 'Javobni o‘zgartirish',
  thanksYes: (n) => `Rahmat, ${n}! Sizni to‘yimizda intizorlik bilan kutamiz.`,
  thanksNo: (n) => `Rahmat, ${n}! Javobingiz uchun minnatdormiz.`,
};

const UZC = {
  ...cyr(UZ),
  months: ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь'],
  monthsNom: ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь'],
  weekdaysShort: ['Ду', 'Се', 'Чо', 'Па', 'Жу', 'Ша', 'Як'],
  gcal: 'Google Тақвимга қўшиш',
  gmap: 'Google Maps',
  ymap: 'Yandex харита',
};

const RU = {
  months: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'],
  monthsNom: ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь'],
  weekdays: ['воскресенье', 'понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота'],
  weekdaysShort: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
  envelopeTo: 'Приглашение',
  envelopeHint: 'Нажмите на печать, чтобы открыть',
  envelopeOpen: 'Открыть приглашение',
  heroCaption: 'Приглашение на свадьбу',
  greeting: 'Дорогой гость!',
  invitation: (g, b) => `Приглашаем вас на свадьбу наших детей — ${g} и ${b}.`,
  closing: 'Ваше присутствие — большая честь для нас!',
  down: 'Вниз',
  respectfully: 'С уважением,',
  when: 'Когда?',
  at: (t) => `в ${t}`,
  gcal: 'Добавить в Google Календарь',
  ics: 'Сохранить в календарь (.ics)',
  countdownTitle: 'До свадьбы осталось',
  units: { days: 'дней', hours: 'часов', minutes: 'минут', seconds: 'секунд' },
  countdownEnded: 'Свадьба состоялась. Спасибо всем, кто был с нами!',
  countdownStarted: 'Свадьба началась! Ждём вас 🤍',
  calTitle: (names) => `${names} — свадьба`,
  where: 'Где?',
  gmap: 'Google Карты',
  ymap: 'Яндекс Карты',
  guestEyebrow: 'Гость свадебного вечера',
  noticesTitle: 'Важные просьбы',
  program: 'Программа свадьбы',
  dress: 'Дресс-код',
  gallery: 'Наши мгновения',
  swipe: 'Листайте →',
  zoom: 'Увеличить фото',
  close: 'Закрыть',
  deadline: (d, m) => `Пожалуйста, ответьте до ${d} ${m}`,
  rsvpTitle: 'Подтвердите присутствие',
  name: 'Ваше имя *',
  phone: 'Ваш номер телефона',
  canCome: 'Сможете прийти? *',
  yes: 'Обязательно приду',
  no: 'К сожалению, не смогу',
  howMany: 'Сколько вас будет?',
  wishes: 'Ваши пожелания',
  send: 'Отправить ответ',
  wishesTitle: 'Пожелания',
  contacts: 'Если есть вопросы',
  musicOn: 'Включить музыку',
  musicOff: 'Выключить музыку',
  langSwitch: 'Сменить язык',
  skip: 'Пропустить',
  preludeBtn: 'Смотреть',
  preludeHint: 'смотрите со звуком',
  closedCall: 'Приём ответов завершён. Если есть вопросы, позвоните по номерам ниже.',
  closed: 'Приём ответов завершён.',
  errName: 'Пожалуйста, введите имя.',
  errAttending: 'Пожалуйста, отметьте, сможете ли прийти.',
  errPhone: 'Номер телефона введён неверно.',
  sending: 'Отправляем…',
  errConfigCall: 'Сейчас не получается принять ответ. Попробуйте чуть позже или позвоните нам.',
  errConfig: 'Сейчас не получается принять ответ. Попробуйте чуть позже.',
  errGeneric: 'Произошла ошибка. Пожалуйста, попробуйте ещё раз чуть позже.',
  errNetwork: 'Проверьте подключение к интернету и попробуйте ещё раз.',
  change: 'Изменить ответ',
  thanksYes: (n) => `Спасибо, ${n}! С нетерпением ждём вас на свадьбе.`,
  thanksNo: (n) => `Спасибо, ${n}, что сообщили! Нам очень приятно.`,
};

export const STR = { uz: UZ, uzc: UZC, ru: RU };
export let T = UZ;
export let LANG = 'uz';
export function setLang(l) {
  LANG = STR[l] ? l : 'uz';
  T = STR[LANG];
}
